import { describe, expect, it } from 'vitest'
import { readFile } from 'node:fs/promises'
import { join } from 'node:path'
import { getDocument } from 'pdfjs-dist/legacy/build/pdf.mjs'
import { decodeText } from '../src/decode/tsbv1'

// End-to-end check of the extraction pipeline against synthetic fixtures
// generated by scripts/make-fixtures.mjs: PDF bytes → PDF.js getTextContent →
// TSBv1 decode. Uses the pdfjs legacy build (no worker) since this runs in Node;
// the browser path in src/pdf/extractText.ts joins text items the same way.

async function extractPages(file: string): Promise<string[]> {
  const data = new Uint8Array(await readFile(join(__dirname, 'fixtures', file)))
  const doc = await getDocument({ data }).promise
  const pages: string[] = []
  for (let i = 1; i <= doc.numPages; i++) {
    const page = await doc.getPage(i)
    const content = await page.getTextContent()
    pages.push(content.items.map((item) => ('str' in item ? item.str : '')).join('\n'))
  }
  await doc.destroy()
  return pages
}

describe('PDF → TSBv1 pipeline', () => {
  it('decodes the transparent-text payload from a staff sheet', async () => {
    const pages = await extractPages('staff-sheet.pdf')
    const team = decodeText(pages[0], 'staff-sheet.pdf')
    expect(team).not.toBeNull()
    expect(team!.warnings).toEqual([])
    expect(team!.mons).toHaveLength(5) // sixth slot is empty and skipped
    expect(team!.mons.map((m) => m.speciesId)).toEqual([
      'incineroar', 'rillaboom', 'flutter-mane', 'urshifu', 'amoonguss',
    ])
    expect(team!.mons[3].formId).toBe('rapid-strike')
    expect(team!.mons[0].stats.spe).toBe('92')
  })

  it('reports no payload for an Open sheet', async () => {
    const pages = await extractPages('open-sheet.pdf')
    expect(decodeText(pages[0], 'open-sheet.pdf')).toBeNull()
  })
})
